export const IPC_CHANNELS = {
    getRuntimeInfo: "runtime:get-info",
    listDevices: "device:list",
    getDeviceInfo: "device:get-info",
    listInstalledApps: "device:list-installed-apps",
    readScreenshotDataUrl: "asset:read-screenshot-data-url",
    startMonitor: "monitor:start",
    stopMonitor: "monitor:stop",
    getMonitorState: "monitor:get-state",
    monitorState: "monitor:state",
    getMonitorCapabilityReport: "monitor:get-capability-report",
    monitorCustomSchema: "monitor:custom-schema",
    monitorCustomSamples: "monitor:custom-samples",
    monitorSample: "monitor:sample",
    listSessions: "report:list-sessions",
    getSession: "report:get-session",
    captureSessionScreenshotEvent: "monitor:capture-session-screenshot-event",
    createSessionEvent: "report:create-session-event",
    updateSessionEvent: "report:update-session-event",
    deleteSessionEvent: "report:delete-session-event",
    renameSession: "report:rename-session",
    deleteSession: "report:delete-session",
    exportSession: "report:export-session",
    openExportDirectory: "report:open-export-directory"
} as const;
